name: tchat_messaging_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  google_sign_in: ^5.0.3
  cloud_firestore: ^2.2.0
  font_awesome_flutter: ^9.0.0
  cached_network_image: ^3.0.0
  image_picker: ^0.7.5+3
  firebase_storage: ^8.1.0
  connectivity: ^3.0.6
  file_picker: ^3.0.2+2
  custom_pop_up_menu: ^1.2.0
  full_screen_image: ^1.0.2
  video_viewer: ^1.2.2
  just_audio: ^0.7.5
  get: ^4.1.4
  adaptive_theme: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

