name: tchat_messaging_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  google_sign_in: ^5.0.3
  cloud_firestore: ^2.2.0
  font_awesome_flutter: ^9.0.0
  floor: ^0.19.1
  get: ^4.1.4

dependency_overrides:
  ffi: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.19.1
  build_runner: ^1.11.5

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

